#SPDX-License-Identifier: MIT-0
---
- name: Install dependencies
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Download latest Google Chrome package
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp
    mode: "644"

- name: Install Google Chrome
  ansible.builtin.apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present

- name: Remove downloaded package
  ansible.builtin.file:
    path: /tmp/google-chrome-stable_current_amd64.deb
    state: absent
